### ISSUE TITLE
Need explanation + some issues

### ISSUE THREAD

**Issue by Nolord** [Zodsmar/SeedSearcherStandaloneTool#47] opened 2020-08-09 09:27 UTC
I like your tool a lot but I need some explanation about what "Incremeter" and "Thread to use" are supposed to mean and to do.
Also some issues and feedbacks:
-the number just next to "Thread to use" is over the "use" word.
-the "Start and Stop the seed searcher" button looks like this : "S...".
-It looks like the  "Randomized Seeds" option verify always the same seeds in the same order.
-There should be a text in the Console Output that says when the seed searcher is enabled.

**Comment by Zodsmar** [comment] 2020-08-11 14:32
So to answer your first two questions the incrementer is how many blocks to skip during a search. Most biomes are at least 50-75 blocks across so this way you check every X amount of block it speeds up searching but depending how big you make it, it can lower your accuracy.
Thread to Use is simply how many threads your computers CPU has this way you can dedicate more CPU power to the tool to speed up searching.

The Start Stop and Thread to Use looking weird are you on Linux? If so this is a known bug. Linux doesn't play nice with JavaFX for some reason.

The randomized seeds starts at 0 and goes up from there again for speed purposes (I am going to be including another setting to randomize it a bit more, but it does this because of structure searching.

The console output seems kinda of redundant. The timer is ticking when the tool is active. If you have a specific reason why it would be useful let me know and I will reevaluate it and add it in.

Thanks!

**Comment by Nolord** [comment] 2020-08-11 15:54
Thanks for you answers. As you can see I'm on the screenshot, I'm not very original, I'm on Windows 10, and I use the .jar version. You can see the 2 bugs that I was talking about.

![insimpécr](https://user-images.githubusercontent.com/33145668/89917405-0d051d00-dbf9-11ea-91f1-42cd876aa9b1.png)

The problem with your randomized seeds option is that if I use a specific set of restrictions for the seed searcher, I always get the same seeds, at the same number of rejected seeds and I feel like it's wasted time until I get to my personal record of rejected seeds.

The console output should show the exact hour of when search has started and ended with number of seeds that it checked so we could make some statistics like the percentage of seeds that respect our restrictions or the number of seeds checked per second for example.

I hope I'm understandable.

**Comment by Zodsmar** [comment] 2020-08-11 19:03
I will look into why its buggy on windows 10. I personally develop on windows 10 and haven't seen this issue. As for the randomization, yes I know what you mean and I am going to work on a way to fix that. I have a few ideas to correct that.

**Comment by DyonR** [comment] 2020-08-20 22:56
The button (and text?) looking weird is **probably** caused by the display scaling of Windows, just a guess

**Comment by Zodsmar** [comment] 2020-08-26 15:32
It most likely is. I need to dig deeper into it to figure out the scaling and make sure its smooth across all devices.

**Comment by racinmat** [comment] 2020-08-30 10:19
I guess it should be somewhere written that number of threads roughly equals number of cores if threads <= cores, as gamers without programming knowledge usually know what core is, but not thread.

**Comment by racinmat** [comment] 2020-08-30 10:21
Maybe the "hotfix" for the people wanting to have staging in the search and to be able to "continue" after some smaller search was done, they could use the not randomized setup and manually set the lower and upper bound. 
I guess that might help people as it's already there, it just doesn't cross immediately mind of someone who does not have experience with high performance distributed computing.

**Comment by Zodsmar** [comment] 2020-09-02 18:05
True Ill rename it Core in the next update

**Comment by Zodsmar** [comment] 2020-12-28 05:50
Renamed and fixed the randomized seeds issue. Will be in the next update

**Closed by Zodsmar** 2020-12-28 05:50 UTC
Labels: Todo, bug
